/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Crazyflie Platform Configuration
 *
 */
#define CONFIG_DECK_LIGHTHOUSE_MAX_N_BS 4
#define CONFIG_APP_PRIORITY 0
#define CONFIG_DECK_FORCE "none"
#define CONFIG_DECK_LEDRING_DEFAULT_EFFECT 6
#define CONFIG_APP_ENABLE 1
#define CONFIG_PLATFORM_CF2 1
#define CONFIG_CPX_UART2_BAUDRATE 576000
#define CONFIG_CONTROLLER_AUTO_SELECT 1
#define CONFIG_MOTORS_ESC_PROTOCOL_ONESHOT125 1
#define CONFIG_DECK_FLOW 1
#define CONFIG_DECK_ACTIVE_MARKER 1
#define CONFIG_ESTIMATOR_KALMAN_ENABLE 1
#define CONFIG_DECK_MULTIRANGER 1
#define CONFIG_DECK_LEDRING 1

#define CONFIG_SYSLINK_DMA 1
#define CONFIG_DECK_LIGHTHOUSE 0
#define CONFIG_DECK_ZRANGER 1
#define CONFIG_ENABLE_CPX 1
#define CONFIG_DECK_OA 1
//#define CONFIG_DECK_USD 1
#define CONFIG_DECK_LEDRING_NBR_LEDS 12
#define CONFIG_DECK_LEDRING_DIMMER 0
#define CONFIG_MOTORS_DEFAULT_BAT_TEST_PWM_RATIO 0
#define CONFIG_SENSORS_MPU9250_LPS25H 0
#define CONFIG_SENSORS_BMI088_I2C 0
#define CONFIG_SENSORS_BMI088_BMP388 0
#define CONFIG_SENSORS_ICM20602 1
#define CONFIG_ENABLE_CPX_ON_UART2 1
#define CONFIG_ESTIMATOR_OUTLIER_FILTERS 1
#define CONFIG_DEBUG_ENABLE_LED_MORSE 1
#define CONFIG_ENABLE_THRUST_BAT_COMPENSATED 1
#define CONFIG_DECK_LOCO 0
#define CONFIG_DECK_LOCO_NR_OF_ANCHORS 8
#define CONFIG_DECK_AI 1
#define CONFIG_DEBUG_QUEUE_MONITOR 1
#define CONFIG_DECK_AI_WIFI_NO_SETUP 1
#define CONFIG_POWER_DISTRIBUTION_QUADROTOR 1
#define CONFIG_APP_STACKSIZE 300
#define CONFIG_MOTORS_DEFAULT_PROP_TEST_PWM_RATIO 0
#define CONFIG_ESTIMATOR_AUTO_SELECT 1
#define CONFIG_DECK_ZRANGER2 1
#define CONFIG_APP_API_TEST 1
#define CONFIG_IMU_MAHONY_QUATERNION 1
#define CONFIG_DECK_BUZZ 1
#define CONFIG_DEBUG 1
#define CONFIG_CROSS_COMPILE "arm-none-eabi-"
#define CONFIG_DECK_LOCO_ALGORITHM_AUTO 1
#define CONFIG_DEBUG_PRINT_ON_CONSOLE 0
#define CONFIG_DEBUG_PRINT_ON_UART 0
#define DEBUG_PRINT_ON_SEGGER_RTT 1
#define ENABLE_UART_DMA 0
//#define UNIT_TEST_MODE 0

#define RADIO_CHANNEL_ADDRESS 0



